---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  TIMEZONE: Europe/London
  NFS_SERVER: 192.168.0.230
  DNS_SERVER: 192.168.0.226
  HA_SERVER: 192.168.0.149
  INGRESS_LB_IP: 192.168.0.193
  MARIADB_SERVICE: mariadb-cluster.databases.svc.cluster.local
  IMMICH_POSTGRES_SERVICE: immich-postgres-rw.databases.svc.cluster.local
  REDIS_SERVICE: redis-master.redis.svc.cluster.local
  AUTHENTIK_OUTPOST_SERVICE: ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local
  PUBLIC_BLOG_DOMAIN: surajremanan.com
