apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: babybuddy
  namespace: babybuddy
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    image:
      repository: linuxserver/babybuddy
      tag: 2.0.4
      pullPolicy: IfNotPresent
    env:
      TZ: Asia/Kolkata
    persistence:
      config:
        enabled: true
        mountPath: /config
        storageClass: longhorn        
  valuesFrom:
    - kind: Secret
      name: babybuddy-secrets
      valuesKey: babybuddy-secrets.yaml
      optional: true