apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  chart:
    spec:
      version: "1.4.2"
  values:
    image:
      repository: filebrowser/filebrowser   
      tag: v2.26.0
    env:
      TZ: "${TIMEZONE}" 
    persistence:
      config:
        enabled: true
        mountpath: /config
        storageClass: longhorn
      data:
        enabled: true
        mountPath: /srv
        type: nfs
        server: "${NFS_SERVER}"
        path: /mnt/ext-hdd/media/
        accessMode: ReadWriteOnce
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations: 
          nginx.ingress.kubernetes.io/proxy-body-size: 5120m
        hosts:
          - 
            host: &host "files.${PUBLIC_DOMAIN}"
            paths:
              -
                path: /
                pathType: Prefix
                service:            
                  name: filebrowser
                  port: 80
        tls: 
          - secretName: "${CERT_SECRET_NAME}"
            hosts:
            - *host          